---
abstract: 'feather-weight transaction management for your DBI handles'
author:
  - 'Shutterstock, Inc. <sstk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DB-Transaction
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0
resources:
  bugtracker: https://github.com/shutterstock/perl-db-transaction/issues
  homepage: https://github.com/shutterstock/perl-db-transaction
  repository: git://github.com/shutterstock/perl-db-transaction.git
version: 0.001
